version: '3'
services:
  nginx:
    build:
      dockerfile: './Dockerfile'
      context: .
    ports:
      - 8080:8080
    volumes:
      - ../..:/workspace:cached
    # Keeps the container running
    command: "tail -F /dev/null"
