version: '3'
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: 'Dockerfile'
    ports:
      - 3000:80
    volumes:
      - ../php/:/var/www/html
      - ..:/workspace:cached

  php:
    build:
      context: ./php
      dockerfile: 'Dockerfile'
    volumes:
      - ..:/workspace:cached

  db:
    image: mysql:latest
    volumes:
      - ../mysql/data:/var/lib/mysql
    environment:
      # Default user is root
      MYSQL_ROOT_PASSWORD: secretpass

  dbadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secretpass
